#!/bin/bash
#
# Usage: script/run <MODE>
# Description: run ngxmrb-image-server container
# Example:
#   $ script/run-target
#   $ script/run-target -d
#

BASE_DIRECTORY=`pwd`
MODE="--rm -it"

if [ $# -eq 1 ]; then
  if [ $1 = "-d" ]; then
    MODE="-d"
  fi
fi

cd $BASE_DIRECTORY
docker kill target > /dev/null 2>&1 || true
docker rm   target > /dev/null 2>&1 || true
docker run \
  $MODE \
  --name ngxmrb-image-server \
  -p 80:80 \
  quay.io/dtan4/ngxmrb-image-server:latest
